### ISSUE TITLE
HTML: alleen een <button> doet niets

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#1]
Er ontbreekt nog wat markup om server-side ook dingen mogelijk te maken (voor het geval dat JS niet laadt). Het is niet nodig om de back-end ook te maken, maar bereid je markup er wel op voor.

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by strexx** [comment]
Ik heb er formulieren om heen gezet die data stuurt naar handler.php. In dit bestand kan je bijvoorbeeld server-side handelingen doen als producten toevoegen in een database.
