### ISSUE TITLE
Body class kan iets beschrijvender

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#2]
`<body class="flexbox">` is niet echt beschrijvend. Kleinigheidje, maar dit kan beter :)

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by strexx** [comment]
ik heb een div#wrapper aangemaakt die om de content heen zit, in plaats van de body te gebruiken als container. En de benaming is nu wrapper, wat duidt als een omhulsel voor content. Verder heb ik flexbox eruit gekicked, want er is geen support voor IE9 en lager en dat maakte het wat fijner om te testen.
