### ISSUE TITLE
Pas op met alt attributen

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#3]
Soms staat er andere informatie in je `alt` attribuut dan de producttitel eronder. Is dat bewust of een bug? En is het misschien handiger om het `alt` attribuut leeg te laten, zeker als de titel er toch zo dicht bij staat? En is `<p><strong>` titel-ig genoeg?

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by strexx** [comment]
Volgens de standaard is het gebruikelijk om verplicht een alt attribuut op je images te zetten. Maar in dit geval, met een titel zo eronder is het overbodig en al beschrijvend genoeg. Dus heb ik deze nu leeg gelaten. De titel heb ik nu een class item__title gegeven. Je zou hier ook een heading element voor kunnen gebruiken als titel van een product.

**Comment by KoopReynders** [comment]
done
