### ISSUE TITLE
Wat is het idee van <a href="#">?

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#4]
Waar zouden de links heen moeten gaan? Wat is de reden dat je hier een `<a>` gebruikt?

**Comment by strexx** [comment]
Goeie vraag. Eigenlijk ben ik dat voorbeeld waarin een <a> werd gebruikt vaak tegengekomen op het web. Hier zat dan een click event aan gebonden met een preventDefault, maar dat is helemaal niet nodig. In de veronderstelling dat deze manier een 'legit' manier was heb ik dat hier ook toegepast. Maar ik heb het nu, naar mijn idee, op een meer semantische manier gemark-upped. Onder andere met een formulier voor server-side afhandeling :)

**Comment by KoopReynders** [comment]
Ik zie dat ieder item een < form > heeft. Veel logischer zou zijn om 1 formulier te maken waar alle producten inzitten, en dan een < checkbox > om producten aan je lijst toe te voegen.

**Comment by strexx** [comment]
Hmm ja, maar als je dan naar een andere pagina gaat of refreshed dan ben je alles kwijt. Tenzij je de producten gelijk opslaat en post als je de producten aanvinkt of moet je altijd eerst submitten voordat je refreshed of naar een andere pagina gaat.
