### ISSUE TITLE
Pas op met !important in je CSS

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#5]
Je gebruikt een aantal keer `!important` in je CSS. Is dat echt nodig daar, of kan dit ook simpeler? Gebruik van `!important` wordt afgeraden, meestal is het een teken van code smell en kun je het met een betere structuur of specifiekere selectors netter oplossen.

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by strexx** [comment]
Ik heb hiervoor extra classes toegevoegd/getoggled op elementen die andere classes overschrijven in de juiste volgorde, in plaats van dat ik ze overschrijf door !important te gebruiken. Dit is inderdaad netter, duidelijker en meer gestructureerd. Ook voor als je de classes nog ergens anders wilt gebruiken in je project.

**Comment by KoopReynders** [comment]
done
