### ISSUE TITLE
Volgorde van prefixes in CSS

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#6]
Pas op met de volgorde van je prefixed properties in CSS (de `box-sizing` regels in dit geval).

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by strexx** [comment]
Ik had hier de volgorde van vendor prefixes voor Chrome en Firefox onderaan staan. Maar dit is niet de juiste manier om op te schrijven. Ik heb ze nu in de juiste volgorde geplaatst zodat de standaard implementatie altijd overschreven wordt.

**Comment by KoopReynders** [comment]
done
