### ISSUE TITLE
JS errors in IE8 (en misschien ook andere versies)

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#7]
Probeer uit te zoeken waarom dit verkeerd gaat (en natuurlijk hoe je het op kunt lossen).

**Comment by strexx** [comment]
IE8 gaf errors vanwege het niet ondersteunen van features die ik gebruik.
- classList (IE10+)
- addEventListener (IE9+)
- forEach (ES5)
- .remove (vervangen met removeChild)

JS geeft nu geen errors meer door middel van feature detection en eigen oplossingen.

**Comment by KoopReynders** [comment]
done
