### ISSUE TITLE
Demo onbruikbaar met alleen toetsenbord

### ISSUE THREAD

**Issue by KrijnHoetmer** [strexx/Browser-Technologies#8]
Wat als ik mijn muis niet kan of wil gebruiken? Hoe voeg ik dan wat toe aan mijn lijstje?

**Comment by KoopReynders** [comment]
Heb je hier iets aan gedaan?

**Comment by strexx** [comment]
Ik laat de buttons om producten toe te voegen nu altijd zien, in plaats van dat je ze alleen ziet als je draganddrop niet ondersteund. Je kunt nu door de pagina tabben en producten toevoegen en verwijderen via de knoppen.

**Comment by KoopReynders** [comment]
done
